version: '3.8'

services:
  backend:
    build: .
    container_name: drinks-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv # Prevent local virtual environment from overriding container's python environment

  frontend:
    build: ./frontend
    container_name: drinks-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent local node_modules from overriding container node_modules
    depends_on:
      - backend
