"""Added Token Blacklist

Revision ID: 936cb480f1db
Revises: b80cee4af1c9
Create Date: 2026-06-03 14:33:49.564113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936cb480f1db'
down_revision = 'b80cee4af1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
